baseURL = '/'
languageCode = 'fr-FR'
title = 'Nehémia Telusma • Portfolio'


[markup.goldmark.parser.attribute]
block = true
title = true

[params.meta]
  description       = "Développeuse Front-End je partage ici avec vous quelques de mes réalisations."
  author            = "Nehémia Telusma"
  favicon           = true
